-- Production data snapshot exported from the dev database.
-- Run in the PROD project's SQL Editor AFTER schema.sql, schema-v2.sql, schema-v3.sql.
-- Clears the schema seed rows first, then loads the real current content.

truncate projects, testimonials, site_content, collection_items;

insert into projects (tag, title, description, img, area, storeys, status, sort_order) values ('Residential', '4-Storey Family Home — Kathmandu', 'Earthquake-resistant RCC structure with modern facade. Full design, approval, and supervised construction.', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80', '2,400 sq.ft', '3 Storeys', 'Completed', 1);
insert into projects (tag, title, description, img, area, storeys, status, sort_order) values ('Design + Build', 'Modern Residence — Lalitpur', 'Contemporary 2-storey home with open-plan living spaces and structural design per NBC standards.', 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80', '1,800 sq.ft', '2 Storeys', 'Completed', 2);
insert into projects (tag, title, description, img, area, storeys, status, sort_order) values ('Structural Design', 'Family Residence — Bhaktapur', 'Full structural analysis and NBC-compliant drawings for a 4-storey family residence. Municipality approved.', 'https://images.unsplash.com/photo-1592595896616-c37162298647?w=800&q=80', '3,100 sq.ft', '4 Storeys', 'Completed', 3);
insert into projects (tag, title, description, img, area, storeys, status, sort_order) values ('Commercial', 'Mixed-Use Building — Pokhara', 'Ground-floor commercial units with residential floors above. Structural design, supervision, and handover.', 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80', '4,200 sq.ft', '5 Storeys', 'Completed', 4);
insert into projects (tag, title, description, img, area, storeys, status, sort_order) values ('Renovation', 'Structural Reinforcement — Biratnagar', 'Full structural assessment and reinforcement of an existing 2-storey home. Seismic retrofitting completed.', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80', '1,600 sq.ft', '2 Storeys', 'Completed', 5);
insert into projects (tag, title, description, img, area, storeys, status, sort_order) values ('Interior Design', 'Luxury Interior — Chitwan', 'Complete interior design, space planning, and premium finishing for a newly constructed residence.', 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80', '2,200 sq.ft', '2 Storeys', 'Completed', 6);

insert into testimonials (project_type, text, name, location, sort_order) values ('3-Storey Residence · Kathmandu', 'हामीले घर बनाउनेभन्दा पहिले धेरै कम्पनीसँग भेट्यौँ। सबैले राम्रो मात्र भन्नुभयो। Afno Ghar ले भने हाम्रो बजेटभित्र के सम्भव छ र के सम्भव छैन भनेर खुलेर भन्नुभयो। त्यही इमानदारीले हामीलाई विश्वास दिलायो। निर्माणको क्रममा साना–ठूला समस्या आए पनि लुकाउनुभएन, समाधानसहित जानकारी दिनुभयो। अहिले घर बनेर परिवारसँग बस्दा एउटा सन्तुष्टि छ—हामीले सही निर्णय गरेका रहेछौँ।', 'Ram Kumar Shrestha', 'Kathmandu', 1);
insert into testimonials (project_type, text, name, location, sort_order) values ('Design + Build · Lalitpur', 'Very professional team. They explained everything clearly, completed on time, and the construction quality is excellent. Our house passed inspection on the first attempt — no issues at all.', 'Sita Maharjan', 'Lalitpur', 2);
insert into testimonials (project_type, text, name, location, sort_order) values ('3 Story Building Design And Build | Bhaktapur', 'घर बनाउने निर्णय हाम्रो जीवनकै सबैभन्दा ठूलो निर्णय थियो। सुरुमा धेरै डर थियो—बजेट बढ्ने हो कि, काम बिग्रिने हो कि, गुणस्तर कस्तो हुने हो भनेर। तर Afno Ghar ले सुरुदेखि अन्तिम चाबी हस्तान्तरणसम्म प्रत्येक चरणमा हामीलाई स्पष्ट जानकारी दियो। अहिले घरमा बस्दा साँच्चै सही टोली रोजेछौँ भन्ने महसुस हुन्छ। धन्यवाद सम्पूर्ण टिमलाई।', 'Bikram Poudel', 'Bhaktapur', 3);
insert into testimonials (project_type, text, name, location, sort_order) values ('2 And Half Story Building · Lalitpur ', 'From design to handover, everything was handled with great care. The engineer assigned to us was always available. The result exceeded what we had imagined.', 'Anita Karki', 'Lalitpur ', 4);
insert into testimonials (project_type, text, name, location, sort_order) values ('Commercial Building · Biratnagar', 'We hired Afno Ghar for our commercial project and they delivered outstanding results. Attention to detail, commitment to deadlines, and honest cost estimates throughout.', 'Nabin Rai', 'Biratnagar', 5);
insert into testimonials (project_type, text, name, location, sort_order) values ('Interior Design · Chitwan', 'The interior design team understood our vision perfectly. They transformed our house into a home we are truly proud of — on budget and without any compromise on quality.', 'Priya Shrestha', 'Chitwan', 6);
insert into testimonials (project_type, text, name, location, sort_order) values ('At hic magna qui et ', 'Consectetur exercit', 'Vel labore dolor ut ', 'Ullamco eligendi ad ', 7);

insert into site_content (key, value) values ('about.img', 'https://mvudiolunhnvcmjjquie.supabase.co/storage/v1/object/public/site-images/about/1784740644677-y87neq.jpeg');
insert into site_content (key, value) values ('contact.title_accent', 'PROJECTS ');

insert into collection_items (collection, data, sort_order) values ('about_trust', '{"label":"Engineering-based approach, not just contractors"}'::jsonb, 1);
insert into collection_items (collection, data, sort_order) values ('about_trust', '{"label":"Transparency in work and communication at every stage"}'::jsonb, 2);
insert into collection_items (collection, data, sort_order) values ('about_trust', '{"label":"Focus on safety, durability, and cost-efficiency"}'::jsonb, 3);
insert into collection_items (collection, data, sort_order) values ('about_trust', '{"label":"On-site supervision and rigorous quality control"}'::jsonb, 4);
insert into collection_items (collection, data, sort_order) values ('counters', '{"end":"70","desc":"Residential buildings across Nepal","label":"Homes Completed","suffix":"+"}'::jsonb, 1);
insert into collection_items (collection, data, sort_order) values ('counters', '{"end":"100","desc":"NBC-compliant engineering drawings","label":"Structural Designs","suffix":"+"}'::jsonb, 2);
insert into collection_items (collection, data, sort_order) values ('counters', '{"end":"1000","desc":"Quality control visits conducted","label":"Site Inspections","suffix":"+"}'::jsonb, 3);
insert into collection_items (collection, data, sort_order) values ('counters', '{"end":"100","desc":"Every project meets national standards","label":"NBC Compliance","suffix":"%"}'::jsonb, 4);
insert into collection_items (collection, data, sort_order) values ('hero_stats', '{"num":"40","label":"Homes Completed","suffix":"+"}'::jsonb, 1);
insert into collection_items (collection, data, sort_order) values ('hero_stats', '{"num":"100","label":"Structural Designs Delivered","suffix":"+"}'::jsonb, 2);
insert into collection_items (collection, data, sort_order) values ('hero_stats', '{"num":"1K","label":"Site Inspections Conducted","suffix":"+"}'::jsonb, 3);
insert into collection_items (collection, data, sort_order) values ('hero_stats', '{"num":"100","label":"NBC Compliance Rate","suffix":"%"}'::jsonb, 4);
insert into collection_items (collection, data, sort_order) values ('process_steps', '{"desc":"We listen to your vision, requirements, and budget in a free first meeting — online or at your site.","title":"Free Consultation","timeline":"Day 1","deliverable":"Project feasibility assessment"}'::jsonb, 1);
insert into collection_items (collection, data, sort_order) values ('process_steps', '{"desc":"Our engineers visit your land, conduct soil assessment, take measurements, and evaluate site conditions.","title":"Site Visit & Survey","timeline":"Day 2–4","deliverable":"Site survey report"}'::jsonb, 2);
insert into collection_items (collection, data, sort_order) values ('process_steps', '{"desc":"We create architectural floor plans, 3D visualizations, and complete structural engineering drawings.","title":"Design & Drawings","timeline":"Week 1–3","deliverable":"Full architectural + structural drawings"}'::jsonb, 3);
insert into collection_items (collection, data, sort_order) values ('process_steps', '{"desc":"We prepare and submit all technical documents for your building permit on your behalf.","title":"Municipality Approval","timeline":"Week 3–6","deliverable":"Approved building permit"}'::jsonb, 4);
insert into collection_items (collection, data, sort_order) values ('process_steps', '{"desc":"Professional construction with supervised execution — foundation, columns, slabs, brickwork, and finishing.","title":"Construction","timeline":"Month 2–14","deliverable":"Fully constructed building"}'::jsonb, 5);
insert into collection_items (collection, data, sort_order) values ('process_steps', '{"desc":"Final quality inspection, snag list resolution, and formal handover with all documentation.","title":"Handover","timeline":"Final Week","deliverable":"Keys + as-built drawings + warranty"}'::jsonb, 6);
insert into collection_items (collection, data, sort_order) values ('process_steps', '{"desc":"Odio consequat Magn","title":"Cumque quisquam quas","timeline":"Cupidatat ducimus a","deliverable":"Labore aut quae ea c"}'::jsonb, 7);
insert into collection_items (collection, data, sort_order) values ('services', '{"desc":"Custom 2D floor plans and 3D visualizations tailored to your lifestyle, plot size, and budget. See your home before a single brick is laid.","icon":"🏛","title":"Architectural Design"}'::jsonb, 1);
insert into collection_items (collection, data, sort_order) values ('services', '{"desc":"Earthquake-resistant design with full load calculations per NBC and IS codes. Your building is engineered to protect your family for decades.","icon":"📊","title":"Structural Analysis"}'::jsonb, 2);
insert into collection_items (collection, data, sort_order) values ('services', '{"desc":"End-to-end construction with professional material management, certified workforce, and strict quality checks from foundation to finishing.","icon":"🏗","title":"Building Construction"}'::jsonb, 3);
insert into collection_items (collection, data, sort_order) values ('services', '{"desc":"Regular on-site inspections, material quality verification, and detailed progress reports — so you always know exactly where your project stands.","icon":"🔍","title":"Site Supervision"}'::jsonb, 4);
insert into collection_items (collection, data, sort_order) values ('services', '{"desc":"We prepare and submit all technical drawings and documents required for building permit approval. Hassle-free, compliant, and fast.","icon":"📋","title":"Municipality Approval"}'::jsonb, 5);
insert into collection_items (collection, data, sort_order) values ('services', '{"desc":"Accurate, itemized cost breakdowns before construction starts. No hidden charges. Plan your budget with complete confidence.","icon":"💰","title":"Cost Estimation"}'::jsonb, 6);
insert into collection_items (collection, data, sort_order) values ('services', '{"desc":"Space planning, material selection, and modern finishing concepts that make every room feel exactly the way you imagined it.","icon":"🛋","title":"Interior Design"}'::jsonb, 7);
insert into collection_items (collection, data, sort_order) values ('trust_bar', '{"label":"NBC Compliant"}'::jsonb, 1);
insert into collection_items (collection, data, sort_order) values ('trust_bar', '{"label":"Earthquake Resistant Design"}'::jsonb, 2);
insert into collection_items (collection, data, sort_order) values ('trust_bar', '{"label":"Municipality Approval Support"}'::jsonb, 3);
insert into collection_items (collection, data, sort_order) values ('trust_bar', '{"label":"Professional Civil Engineers"}'::jsonb, 4);
insert into collection_items (collection, data, sort_order) values ('trust_bar', '{"label":"Transparent Cost Estimation"}'::jsonb, 5);
insert into collection_items (collection, data, sort_order) values ('why_items', '{"desc":"Every structure we design is earthquake-resistant and fully NBC-compliant. Your family''s safety is never negotiated — it is engineered.","icon":"🛡","badge":"Safety","title":"Safety First, Always"}'::jsonb, 1);
insert into collection_items (collection, data, sort_order) values ('why_items', '{"desc":"We calculate, analyze, and verify — no guesswork. Load calculations, structural analysis, and field checks at every stage.","icon":"📐","badge":"Precision","title":"Engineering Precision"}'::jsonb, 2);
insert into collection_items (collection, data, sort_order) values ('why_items', '{"desc":"You receive a detailed cost breakdown before construction begins. No hidden charges, no last-minute surprises — just honest numbers.","icon":"💰","badge":"Transparency","title":"Transparent Budgeting"}'::jsonb, 3);
insert into collection_items (collection, data, sort_order) values ('why_items', '{"desc":"Premium materials, certified workers, and strict quality checks at foundation, column, slab, and finishing stages.","icon":"🏗","badge":"Quality","title":"Quality Construction"}'::jsonb, 4);
insert into collection_items (collection, data, sort_order) values ('why_items', '{"desc":"A dedicated engineer is assigned to your project. Get real-time updates, progress reports, and answers whenever you need them.","icon":"📞","badge":"Support","title":"Dedicated Project Support"}'::jsonb, 5);
insert into collection_items (collection, data, sort_order) values ('why_items', '{"desc":"Aut commodo optio u","icon":"","badge":"Sed consectetur modi","title":"Iste nisi voluptatem"}'::jsonb, 6);
